# Generated by Django 3.2.10 on 2022-01-04 00:02

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='実行日時')),
                ('command', models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(regex='^(?!.*(\\&|\\||\\>|\\<|\\;|\\`)).*$')], verbose_name='実行したコマンド')),
            ],
        ),
    ]
